spring.application.name=backend

# Configuración de base de datos MySQL (Docker)
spring.datasource.url=jdbc:mysql://localhost:3307/pisofacil
spring.datasource.username=admin
spring.datasource.password=admin123

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=PisoFacilSecretKeyQueDebeSerLargaAlMenos256BitsParaHMACSHA
jwt.expiration=86400000

# Fija el prefijo /api para TODOS los controladores automáticamente
server.servlet.context-path=/api

# CONFIGURACIÓN DE PUERTO
server.port=8081

# Ruta absoluta al directorio de fotos (independiente del working directory del proceso)
app.uploads.dir=/home/oscarfh06/Documentos/OSCAR/2DAM/TFG PisoFacil/backend/uploads/fotos
